name: Publish Docker image
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-24.04
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        # Логинимся в докер-хаб с использованием секретного токена
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: ./server/
        # Сохраняем свежий образ на ДокерХабе
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/devops-2026:latest

  touch-k8s-manifest:
    needs: [ push_to_registry ]
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    
    # Подменяем дату (обновляем манифест)
    - name: Insert release date
      run: 'sed -i "s/release-date: .*$/release-date: s`date +%s`/g" ./server-k8s-manifests/app.yml'

    # Сохраняем изменения манифеста в ветке release
    - name: Commit manifest
      run: |
        git config --global user.name 'Release Runner'
        git config --global user.email 'runner@users.noreply.github.com'
        git commit -am "Release"
        git push --force origin main:release